# Generated by Django 5.1 on 2024-09-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='client',
            field=models.CharField(default='Marvan', max_length=255),
        ),
    ]
