# Generated by Django 5.1 on 2024-09-10 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0003_alter_job_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='job',
            name='deadline',
        ),
    ]
