# Generated by Django 5.1 on 2024-08-28 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_cnic_alter_profile_date_of_joining_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='development_team',
        ),
        migrations.RemoveField(
            model_name='project',
            name='responsible_person',
        ),
        migrations.DeleteModel(
            name='DevelopmentTeam',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
