# Generated by Django 5.1 on 2024-10-18 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_workexperience_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='users.profile'),
        ),
    ]
