# Generated by Django 5.1 on 2024-10-18 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_workexperience_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='duration',
        ),
    ]
