# Generated by Django 5.1 on 2024-08-30 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('members', models.ManyToManyField(related_name='development_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('client_name', models.CharField(max_length=255)),
                ('tech_stack', models.CharField(max_length=255)),
                ('project_documents', models.FileField(upload_to='project_documents/')),
                ('git_link', models.URLField()),
                ('live_link', models.URLField(blank=True, null=True)),
                ('figma_link', models.URLField(blank=True, null=True)),
                ('industry', models.CharField(max_length=255)),
                ('keywords', models.CharField(max_length=255)),
                ('logo_icon', models.ImageField(upload_to='project_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('development_team', models.ManyToManyField(related_name='team_projects', to=settings.AUTH_USER_MODEL)),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
