# Generated by Django 5.1 on 2024-09-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_keyword_techstack_remove_project_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='logo_icon',
            field=models.ImageField(blank=True, null=True, upload_to='project_logos/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_documents',
            field=models.FileField(blank=True, null=True, upload_to='project_documents/'),
        ),
    ]
