# Generated by Django 5.1 on 2024-09-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_document_project_rating_project_server_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='document-1', max_length=255),
        ),
    ]
