# Generated by Django 5.1 on 2024-10-23 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gora', models.TextField(null=True)),
                ('connects', models.IntegerField(default=0)),
                ('account_executive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_account_executive', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_assigned', to=settings.AUTH_USER_MODEL)),
                ('division_lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_division_lead', to=settings.AUTH_USER_MODEL)),
                ('lead_gen_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_lead_gen_manager', to=settings.AUTH_USER_MODEL)),
                ('sdr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_sdr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_duration', models.CharField(max_length=100)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project_start_date', models.DateField()),
                ('estimated_closing_date', models.DateField()),
                ('milestone', models.TextField()),
                ('status', models.CharField(choices=[('win', 'Win'), ('lost', 'Lost')], default='pending', max_length=10)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.lead')),
            ],
        ),
    ]
