# Generated by Django 5.1 on 2024-11-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_lead_status_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='lead_documents/'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('opportunity', 'Opportunity'), ('quotation', 'Quotation'), ('win', 'Win'), ('lost', 'Lost')], default='open', max_length=20),
        ),
    ]
