# Generated by Django 5.1 on 2024-11-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_document_file_alter_lead_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='lead',
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='leads', to='cms.document'),
        ),
    ]
