# Generated by Django 5.1 on 2024-11-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_remove_document_lead_document_name_lead_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='approval_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('disapproved', 'DisApproved'), ('pending', 'Pending')], default='open', max_length=20),
        ),
    ]
