# Generated by Django 5.1 on 2024-11-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_lead_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='approval_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('disapproved', 'DisApproved'), ('pending', 'Pending')], default='approved', max_length=20),
        ),
    ]
