# Generated by Django 5.1 on 2024-11-06 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_alter_lead_approval_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='estimated_closing_date',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='estimated_cost',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='estimated_duration',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='milestone',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='project_start_date',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='status',
        ),
        migrations.AddField(
            model_name='quotation',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_name',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment_duration',
            field=models.IntegerField(choices=[(5, '5 days'), (15, '15 days'), (25, '25 days'), (30, '30 days')], default=25),
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment_list',
            field=models.CharField(choices=[('PKR', 'PKR'), ('USD', '$')], default='USD', max_length=3),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cms.quotation')),
            ],
        ),
    ]
