# Generated by Django 5.1 on 2024-11-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_alter_quotation_payment_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='payment_duration',
            field=models.IntegerField(choices=[(15, '15 days'), (30, '30 days'), (30, '45 days'), (30, '60 days')], default=25),
        ),
    ]
