# Generated by Django 5.1 on 2024-11-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_alter_quotation_payment_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='payment_list',
            field=models.CharField(choices=[('PKR', 'PKR'), ('USD', 'USD')], default='USD', max_length=3),
        ),
    ]
