# Generated by Django 5.1 on 2024-11-13 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_alter_quotation_payment_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cms.lead'),
        ),
    ]
