# Generated by Django 5.1 on 2024-11-13 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_alter_order_quotation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quotation',
            new_name='lead',
        ),
    ]
