# Generated by Django 5.1 on 2024-11-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_activity_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='communication_note',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
