# Generated by Django 5.1 on 2024-11-14 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_lead_communication_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='communication_note',
            new_name='communication_notes',
        ),
    ]
