# Generated by Django 5.1 on 2024-11-18 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_lead_created_at_quotation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='quotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation', to='cms.quotation'),
        ),
    ]
