# Generated by Django 5.1 on 2024-11-18 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_lead_quotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='quotation',
        ),
        migrations.AddField(
            model_name='quotation',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='cms.lead'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='communication_notes',
            field=models.TextField(blank=True, default='NULL', null=True),
        ),
    ]
