# Generated by Django 5.1 on 2024-11-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_remove_lead_quotation_quotation_lead_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='content',
            new_name='note',
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
