# Generated by Django 5.1 on 2024-12-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0026_folder_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
