# Generated by Django 5.1 on 2024-12-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0028_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='total_size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
